name: Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:8-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew build bintrayUpload -x test --stacktrace
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}